title: "研究ノート"
description: "研究関連の情報をまとめたノート（新4年生向けの情報が多めです）"
theme: just-the-docs

baseurl: "/note"
url: "https://takahiro-kawaguchi.github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
